In [2]:
import torch

In [15]:
torch.argmax(a, dim=1)

tensor([2, 2, 2, 2])

In [17]:
a[torch.arange(4), torch.argmax(a, dim=1)]

tensor([1.3538, 1.4310, 1.1114, 1.9685])

In [13]:
a

tensor([[-0.2337, -0.3816,  1.3538,  0.2232],
        [-0.5299, -0.2436,  1.4310,  0.6256],
        [ 0.0385, -0.5308,  1.1114,  0.5465],
        [ 0.6669,  1.9456,  1.9685,  1.3794]])

In [14]:
a[torch.arange(4) ,]

tensor([1.3538, 1.4310, 1.1114, 1.9685])